apiVersion: comparo/v1
kind: Schema
metadata:
  name: Echo (GET)
  id: schema.echo-get
  description: The structure postman-echo's GET /get endpoint returns.
spec:
  type: object
  required:
    - args
    - headers
    - url
  properties:
    args:
      type: object
    headers:
      type: object
    url:
      type: string
